USE master;
ALTER DATABASE Föy1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE Föy1 
FROM DISK = '<path>\Föy1_Yedek.bak'
WITH REPLACE, RECOVERY, STATS = 10;

ALTER DATABASE Föy1 SET MULTI_USER;
