version: '3.8'

services:
  hazelcast:
    image: hazelcast/hazelcast:3.12.12
    container_name: hazelcast-cluster
    environment:
      - HAZELCAST_CLUSTER_NAME=my-cluster
      - HAZELCAST_PASSWORD=hazelcast-password
    ports:
      - "5701:5701"
    networks:
      - my-network

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
